[project]
name = "islp-textbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pbeards", email = "peterbeardsmore@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dash>=4.4.1",
    "islp>=0.4.1",
    "numpy>=2.5.3",
    "plotly>=7.0.0",
]

[project.scripts]
islp = "islp_textbook:main"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.6",
    "ty>=0.0.79",
]
